version: "3.5"
networks:
  ev_network:
    driver: overlay
    external: false
volumes:
  mongo-data: {}

services:
  mongodb:
    image: mongo:4.0
    ports:
    - 27017:27017
    volumes:
    - "mongo-data:/data/db"
    env_file:
    - ev_mongo.env
    command: --replSet 'rs0'
    networks:
      ev_network:
        aliases:
        - ev_mongo
    extra_hosts:
    - ev_mongo:127.0.0.1
  enablereplset:
    depends_on:
    - mongodb
    build:
      context: replica
    links:
    - mongodb
    networks:
    - ev_network
    environment:
      WAIT_HOSTS: ev_mongo:27017
      WAIT_HOSTS_TIMEOUT: 90
  mailserver:
    image: djfarrelly/maildev
    ports:
    - 1025:25
    - 1080:80
    networks:
    - ev_network
    command: bin/maildev --web 80 --smtp 25 --verbose --incoming-user evse-mail-user --incoming-pass evse-mail-pwd
