version: 0.2
phases:
  runtime-versions:
    nodejs: 10
  install:
    commands:
      - echo Entered the install phase...
      - npm install
  build:
    commands:
      - echo Entered the build phase...
      - npm run build:prod
artifacts:
  type: zip
  files:
    - package.json
    - package-lock.json
    - 'dist/**/*'
