version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12.16.1
    commands:
      - npm install
  build:
    commands:
      - npm run build:prod
artifacts:
  type: zip
  files:
    - '**/*'
