version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - npm run build:prod
artifacts:
  type: zip
  files:
    - package.json
    - package-lock.json
    - appspec.yml
    - 'dist/**/*'
