version: "3.5"
networks:
  ev_network:
    driver: bridge
services:
  server:
    build:
      context: ..
      dockerfile: Dockerfile.production
    ports:
    - 90:90
    - 8081:8081
    - 8000:8000
    - 8010:8010
    - 9090:9090
    - 9292:9292
    external_links:
    - evse_mongodb_1
    - evse_mailserver_1
    environment:
      WAIT_HOSTS: ev_mongo:27017
      WAIT_HOSTS_TIMEOUT: 90
      WAIT_AFTER_HOSTS: 3
    networks:
    - ev_network