name: Unit Tests CI

on:
  pull_request:
    branches:
      - master-qa
  push:
    branches:
      - unit-tests-ci

jobs:
  unit-tests:
    env:
      CI: true

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build testing environment
      run: cd docker && make SUBMODULES_INIT=false
    - name: npm install
      run: npm ci
    # - name: npm run test:createContext
    #     run: |
    #       cp test/config-local-ci.json test/config/local.json
    #       npm run test:createContext
    # - name: npm test
    #     run: npm test

  unit-tests-submodules:
    env:
      CI: true

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.ACTION_ACCESS_SUB_MODULES_PRIVATE_REPOS }}
        submodules: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build testing environment
      run: cd docker && make
    - name: npm install
      run: npm ci
    # - name: npm run test:createContext
    #   run: |
    #     cp test/config-local-ci.json test/config/local.json
    #     npm run test:createContext
    # - name: npm test
    #     run: npm test

